name: "Deploy GCP Resources and Publish Docker Image"

on: 
    push:
        branches:
        - main

jobs: 
    terraform-deployment:
      name: "Terraform Deployment" 
      runs-on: ubuntu-latest
      defaults:
          run:
              shell: bash
              working-directory: ./infra

      steps: 
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Setup Terraform with specified version on the runner
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.4.4
            
        - name: Terraform variables
          run: |-
            cat > pipeline.auto.tfvars <<EOF
            project_id = "${{ vars.GCP_PROJECT_ID }}" 
            region = "${{ vars.GCP_REGION }}" 
            zone = "${{ vars.GCP_ZONE }}"
            EOF
            
        - name: Terraform init
          run: terraform init 
          env: 
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Plan
          run: terraform plan -input=false
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Terraform Apply
          run: terraform apply -auto-approve -input=false
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
            
    publish-dockerImage:
      name: "Publish Docker Image" 
      runs-on: ubuntu-latest
      needs: terraform-deployment
      defaults:
        run:
          shell: bash
          working-directory: ./
          
      steps: 
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup gcloud docker
          run: |
            gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet
          env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
        - name: Docker Compose Build
          run: |
            docker-compose build

        # Should probably be configured by variables, but hey, it's a demo 
        - name: Docker Compose Tag
          run: |
            docker tag cloud-app:latest europe-north1-docker.pkg.dev/showcase-cloudfunction/app-repo/cloud-app:latest

        - name: Push Docker Image
          run: |
            docker push europe-north1-docker.pkg.dev/showcase-cloudfunction/app-repo/cloud-app:latest
          env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}