name: "Deploy Terraform resources"

on: 
    push:
        branches:
        - main

jobs: 
    terraform-deployment:
        name: "Terraform Deployment" 
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./infra

        steps: 
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Terraform with specified version on the runner
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.4.4
            
            - name: Terraform variables
              run: |-
                cat > pipeline.auto.tfvars <<EOF
                project_id = "${{ vars.GCP_PROJECT_ID }}" 
                region = "${{ vars.GCP_REGION }}" 
                zone = "${{ vars.GCP_ZONE }}"
                EOF
            
            - name: Terraform init
              run: terraform init 
              env: 
                GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

            - name: Terraform Plan
              run: terraform plan -input=false
              env:
                GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

            - name: Terraform Apply
              run: terraform apply -auto-approve -input=false
              env:
                GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}