name: Test Docker Image
on: 
    pull_request:
        branches: [main]
jobs:
    Run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Docker Image
              run: docker build -t test-image .
            
            - name: Run Docker Image
              run: docker run test-image
              